# 行列の紹介
一般的に、行列は行と列に配置された数値の配列です。

## 行列と行列の表記法
行列は次のように数値を並べて行と列を構成します。


$$
A = \begin{bmatrix}
  1 & 2 & 3 \\
  4 & 5 & 6
 \end{bmatrix}
$$

行列は通常、大文字で命名されることに注意してください。行列の「要素」は、行と列の添字で小文字の同等物を使用して参照します。

$$
A = \begin{bmatrix}
  a_{1,1} & a_{1,2} & a_{1,3} \\
  a_{2,1} & a_{2,2} & a_{2,3}
 \end{bmatrix}
$$

Pythonでは、次のように2次元の`numpy.array`として行列を定義できます。

In [1]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
print (A)

[[1 2 3]
 [4 5 6]]


また、`numpy.array`の特殊なサブクラスである`numpy.matrix`タイプも使用できます。

In [2]:
import numpy as np

M = np.matrix([[1,2,3],
               [4,5,6]])
print (M)

[[1 2 3]
 [4 5 6]]


`array`タイプと`matrix`タイプの間には、特に乗算に関して動作の違いがあります（これについては後で詳しく説明します）。どちらを使用しても構いませんが、ベクトルと行列の両方を扱う必要がある経験豊富なPythonプログラマーは、一貫性のために`array`タイプを好む傾向があります。

## 行列演算
行列は一般的な算術演算をサポートしています。

### 行列の加算
同じサイズの2つの行列を加算するには、各行列の対応する要素を単純に加算します。

$$
\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix}+ \begin{bmatrix}6 & 5 & 4 \\3 & 2 & 1\end{bmatrix} = \begin{bmatrix}7 & 7 & 7 \\7 & 7 & 7\end{bmatrix}
$$

この例では、2つの行列（`A`と`B`とします）を加算しています。各行列は3列2行（2x3行列と表現します）。これらを加算すると、a<sub>1,1</sub> + b<sub>1,1</sub>、a<sub>1,2</sub> + b<sub>1,2</sub>、a<sub>1,3</sub> + b<sub>1,3</sub>、a<sub>2,1</sub> + b<sub>2,1</sub>、a<sub>2,2</sub> + b<sub>2,2</sub>、a<sub>2,3</sub> + b<sub>2,3</sub>の値を持ち、同じ次元の新しい行列が作成されます。この例では、対応する要素の各ペア（1と6、2と5、3と4など）が7になります。

Pythonで試してみましょう。

In [3]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[6,5,4],
              [3,2,1]])
print(A + B)

[[7 7 7]
 [7 7 7]]


### 行列の減算
行列の減算は行列の加算と同様に機能します。

$$
\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix}- \begin{bmatrix}6 & 5 & 4 \\3 & 2 & 1\end{bmatrix} = \begin{bmatrix}-5 & -3 & -1 \\1 & 3 & 5\end{bmatrix}
$$

これを実行するPythonコードは次のとおりです。

In [ ]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[6,5,4],
              [3,2,1]])
print (A - B)

#### 適合性
前の例では、行列を加算および減算できました。これは、`オペランド`（操作対象の行列）が特定の操作（この場合は加算または減算）に対して`適合性`があるためです。加算および減算に対して適合性があるには、オペランドは同じ行数と列数を持っている必要があります。乗算などの他の操作には異なる適合性要件があり、これについては後で詳しく説明します。

### 負の行列
行列の負は、各要素の符号が反転した行列です。

$$
C = \begin{bmatrix}-5 & -3 & -1 \\1 & 3 & 5\end{bmatrix}
$$

$$
-C = \begin{bmatrix}5 & 3 & 1 \\-1 & -3 & -5\end{bmatrix}
$$

Pythonで見てみましょう。

In [ ]:
import numpy as np

C = np.array([[-5,-3,-1],
              [1,3,5]])
print (C)
print (-C)

### 行列の転置
行列の行と列の向きを入れ替える（`転置`する）ことができます。これは上付き文字`T`で示されます。

$$
\begin{bmatrix}1 & 2 & 3 \\4 & 5 & 6\end{bmatrix}^{T} = \begin{bmatrix}1 & 4\\2 & 5\\3 & 6 \end{bmatrix}
$$

Pythonでは、`numpy.array`と`numpy.matrix`の両方に`T`関数があります。

In [ ]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
print(A.T)